##############################################################################
#
#    The MIT License (MIT)
#
#    Copyright (c) 2014 - 2026 Vivante Corporation
#
#    Permission is hereby granted, free of charge, to any person obtaining a
#    copy of this software and associated documentation files (the "Software"),
#    to deal in the Software without restriction, including without limitation
#    the rights to use, copy, modify, merge, publish, distribute, sublicense,
#    and/or sell copies of the Software, and to permit persons to whom the
#    Software is furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in
#    all copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
#    DEALINGS IN THE SOFTWARE.
#
##############################################################################

SDK_DIR       ?= /srv/armv7-thumb-min-debug/root/VGLite
KERNEL_DIR    ?= /home/software/Linux/linux-2.6.29
CROSS_COMPILE ?= /home/software/Linux/arm-2011.09/bin/arm-none-linux-gnueabi-
CC            ?= $(CROSS_COMPILE)gcc

DEBUG       ?= 0
CPU_ARCH    ?= armv7-a
FLOAT_ABI   ?=
ENABLE_PCIE ?= 0

ifneq ($(CPU_ARCH),0)
CFLAGS += -march=$(CPU_ARCH)
endif
ifneq ($(FPU),)
  CFLAGS += -mfpu=$(FPU)
endif
ifneq ($(FLOAT_ABI),)
  CFLAGS += -mfloat-abi=$(FLOAT_ABI)
endif

ifeq ($(VG_GL_SUPPORT),1)
  CFLAGS            += -DVG_GL_SUPPORT=1
else
  CFLAGS            += -DVG_GL_SUPPORT=0
endif

CFLAGS += -fPIC -std=c99 -fno-strict-aliasing -D_GNU_SOURCE

ifeq ($(DEBUG), 1)
CFLAGS += -g -O0 -DDEBUG -D_DEBUG -Wno-cpp
else
CFLAGS += -O2 -Werror
endif

